apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: tweet-uploading-service
  name: tweet-uploading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tweet-uploading-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/tweet-analyzer-final-project-default: "true"
        io.kompose.service: tweet-uploading-service
    spec:
      containers:
        - env:
            - name: TWITTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter-api-secrets
                  key: TWITTER_API_KEY
            - name: TWITTER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter-api-secrets
                  key: TWITTER_API_SECRET_KEY
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter-api-secrets
                  key: TWITTER_ACCESS_TOKEN
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-api-secrets
                  key: TWITTER_ACCESS_TOKEN_SECRET
          image: tweet-uploading-service:latest
          name: tweet-uploading-service
          ports:
            - containerPort: 3020
              hostPort: 3020
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
