apiVersion: v1
kind: Secret
metadata:
  name: twitter-api-secrets
type: Opaque
data:
  TWITTER_API_KEY: TE9sYjFlMVdSVTZIUDhrREZ4czJjQzBVZg==
  TWITTER_API_SECRET_KEY: SWZ3RmZjY3puYlVvWmpRS2xuRzJqNGhDZWJVanlRVDA2YTlycElvV0dTdW90TDFrSUo=
  TWITTER_ACCESS_TOKEN: MTc2NTgxNTU0MTAxNTQ4MjM2OC1IR1I2YjhXU2ZLSDBlbklXbmRia0cyRDdVbG4wdXM=
  TWITTER_ACCESS_TOKEN_SECRET: WnIyTnFEeDc2NFd4VkZJam9rYWxGZ1F3MkdaQUZRWml5UjJDRFo1djhkbDE4
